if boot fails try looking for a device with label GEEXBOX before giving up

diff --git a/packages/initrd/scripts/linuxrc b/packages/initrd/scripts/linuxrc
--- a/packages/initrd/scripts/linuxrc
+++ b/packages/initrd/scripts/linuxrc
@@ -234,6 +234,13 @@ case "$BOOT" in
     ;;
 esac
 
+if ! test -n "$GEEXBOX" -a -r "$GEEXBOX"/bin.tar* ; then
+  # if boot fails look for a device with label GEEXBOX before giving up
+  progress 24000 "Boot Device Detection failed, trying another way"
+  BOOT_LABEL=GEEXBOX
+  boot_from_hdd
+fi
+
 if test -n "$GEEXBOX" -a -r "$GEEXBOX"/bin.tar* ; then
   progress 25000 "copying system into ram"
   cp -a "$GEEXBOX/etc" /
