busybox-init : fix umount of /disk

diff --git a/packages/busybox-init/scripts/shutdown b/packages/busybox-init/scripts/shutdown
--- a/packages/busybox-init/scripts/shutdown
+++ b/packages/busybox-init/scripts/shutdown
@@ -46,6 +46,23 @@ mount --move /oldroot/.data /data
 mount -o remount,del:/data /oldroot
 umount /data                                         # Umount cleanly /data
 umount /oldroot
+mount -o remount,ro /
+mount -o remount,ro /sys
+mount -o remount,ro /dev
+mount -o remount,ro /run
+if ! umount -n /disk ; then
+  echo "Doing lazy umount of /disk ..."
+  device=`cat /proc/mounts | grep "/disk " | cut -d" " -f1`
+  umount -l /disk
+  echo " Trying to remount it ..."
+  if mount $device /disk ; then
+    echo "Success... Now un-mounting it"
+    umount /disk
+  else
+    echo "An error occurs, please check you disk"
+  fi
+fi
+
 cat /proc/mounts                                     # Just to see ...
 
 case "$1" in
