linux: new location for default kernel configuration file

diff --git a/packages/linux/unpack b/packages/linux/unpack
--- a/packages/linux/unpack
+++ b/packages/linux/unpack
@@ -22,9 +22,18 @@ case $TARGET_ARCH in
     ;;
 esac
 
-KERNEL_CFG_FILE=$PACKAGES/$1/config/$1.$TARGET_ARCH.conf
-[ -f $PACKAGES/$1/config/$1.$TARGET_PLATFORM.conf ] && KERNEL_CFG_FILE=$PACKAGES/$1/config/$1.$TARGET_PLATFORM.conf
-[ -n "$CUSTOM_KERNEL_CFG_FILE" ] && KERNEL_CFG_FILE=$CUSTOM_KERNEL_CFG_FILE
+# try to guess the appropriate kernel configuration file
+KERNEL_CFG_FILE="$CONFIG_PLATFORM/$1.conf"
+
+[ ! -f $KERNEL_CFG_FILE ] && \
+  KERNEL_CFG_FILE="$PACKAGES/$1/config/$1.$TARGET_ARCH.conf"
+
+if [ ! -f "$KERNEL_CFG_FILE" ]; then
+  echo "Unable to find a matching kernel configuration file !!"
+  exit 1
+fi
+
+echo "Using kernel config from: $KERNEL_CFG_FILE"
 
 sed -i -e "s|^HOSTCC[[:space:]]*=.*$|HOSTCC = $HOST_CC|" \
        -e "s|^HOSTCXX[[:space:]]*=.*$|HOSTCXX = $HOST_CXX|" \
