kodi: Auto-detect kodi version in addon sync script

diff --git a/packages/multimedia/kodi/addon-sync b/packages/multimedia/kodi/addon-sync
--- a/packages/multimedia/kodi/addon-sync
+++ b/packages/multimedia/kodi/addon-sync
@@ -8,11 +8,16 @@ fi
 . config/options
 get_meta kodi
 
+$SCRIPTS/unpack kodi
 
-ADDON_KODIVER="16"
 ADDON_BASE="$PKG_BUILD_DIR/project/cmake/addons"
 ADDON_PKG_PREFIX="$ROOT/packages/multimedia/kodi-addon-"
+ADDON_KODIVER=$(grep "VERSION_MAJOR" "$PKG_BUILD_DIR/version.txt" | cut -f2 -d' ')
 
+if [ -z "$ADDON_KODIVER" ]; then
+  echo "Cannot determine Kodi version"
+  exit 1
+fi
 
 # fetch addon repository
 (cd $ADDON_BASE/bootstrap; cmake . -DCMAKE_INSTALL_PREFIX=../addons; make)
