add require_glibc function to allow packages to require glibc

diff --git a/config/path b/config/path
--- a/config/path
+++ b/config/path
@@ -202,4 +202,11 @@ kernel_path() {
   ls -d $ROOT/$BUILD/linux*
 }
 
+require_glibc() {
+  if [ "$TARGET_LIBC" != glibc ]; then
+    echo "$1 requires glibc, aborting."
+    exit 1
+  fi
+}
+
 INCLUDED_LANGS="en $MENU_LANG $INCLUDED_LANGS"
