toolchain: add some euristics for out-of-tree builds in do_configure

diff --git a/config/path b/config/path
--- a/config/path
+++ b/config/path
@@ -452,6 +452,7 @@ do_configure () {
   local buildfor=target
   local buildhost=$TARGET_NAME
   local buildconf="--enable-shared --disable-static"
+  local configure
 
   if [ "$1" = target ]; then
     buildfor=target
@@ -465,6 +466,15 @@ do_configure () {
     shift
   fi
 
+  if [ -x ./configure ]; then
+    configure=./configure
+  elif [ -x ../configure ]; then
+    configure=../configure
+  else
+    echo "Cannot find configure script, aborting."
+    exit 1
+  fi
+
   setup_toolchain $buildfor
 
   export CFLAGS="$CFLAGS $local_cflags"
@@ -472,7 +482,7 @@ do_configure () {
   export CPPFLAGS="$CPPLAGS $local_cppflags"
   export LDFLAGS="$LDFLAGS $local_ldflags"
 
-  ./configure --host=$buildhost \
+  $configure --host=$buildhost \
               --build=$HOST_NAME \
               --prefix=/usr \
               --sysconfdir=/etc \
