add require_cxx function to allow packages to require C++ toolchain support

diff --git a/config/path b/config/path
--- a/config/path
+++ b/config/path
@@ -209,4 +209,11 @@ require_glibc() {
   fi
 }
 
+require_cxx() {
+  if [ "$TOOLCHAIN_CXX" != yes ]; then
+    echo "$1 requires C++ toolchain support, aborting."
+    exit 1
+  fi
+}
+
 INCLUDED_LANGS="en $MENU_LANG $INCLUDED_LANGS"
