toolchain: abort build if we use CodeSourcery and CODESOURCERY_ROOT is not set

diff --git a/config/toolchain b/config/toolchain
--- a/config/toolchain
+++ b/config/toolchain
@@ -44,6 +44,10 @@ case $TARGET_ARCH in
 esac
 
 if [ "$TOOLCHAIN_TYPE" = codesourcery ]; then
+  if [ ! -d "$CODESOURCERY_ROOT" ]; then
+    echo "Cannot find CodeSourcery root \"$CODESOURCERY_ROOT\", aborting..."
+    exit 1
+  fi
   TARGET_NAME=$TARGET_ARCH-none-linux-gnu$TARGET_ABI
   TARGET_LIBC=codesourcery-libc
   case "$TARGET_SUBARCH" in
