toolchain: add optiona support for CodeSourcery toolchain

diff --git a/config/toolchain b/config/toolchain
--- a/config/toolchain
+++ b/config/toolchain
@@ -43,16 +43,38 @@ case $TARGET_ARCH in
     ;;
 esac
 
-# determine target name
-case $TARGET_LIBC in
-  uclibc)
-    TARGET_NAME=$TARGET_SUBARCH-geexbox-linux-uclibc
-    ;;
+if [ "$TOOLCHAIN_TYPE" = codesourcery ]; then
+  TARGET_NAME=$TARGET_ARCH-none-linux-gnu$TARGET_ABI
+  TARGET_LIBC=codesourcery-libc
+  case "$TARGET_SUBARCH" in
+    armv4)
+      CODESOURCERY_SYSROOT=$CODESOURCERY_ROOT/$TARGET_NAME/libc/armv4t
+      ;;
 
-  glibc|eglibc)
-    TARGET_NAME=$TARGET_SUBARCH-geexbox-linux-gnu$TARGET_ABI
-    ;;
-esac
+    armv5)
+      CODESOURCERY_SYSROOT=$CODESOURCERY_ROOT/$TARGET_NAME/libc
+      ;;
+
+    armv7)
+      CODESOURCERY_SYSROOT=$CODESOURCERY_ROOT/$TARGET_NAME/libc/thumb2
+      ;;
+
+    *)
+      echo "$TARGET_SUBARCH is not currently supported with CodeSourcery toolchain, aborting..."
+      exit 1
+  esac
+else
+  # determine target name
+  case $TARGET_LIBC in
+    uclibc)
+      TARGET_NAME=$TARGET_SUBARCH-geexbox-linux-uclibc
+      ;;
+
+    glibc|eglibc)
+      TARGET_NAME=$TARGET_SUBARCH-geexbox-linux-gnu$TARGET_ABI
+      ;;
+  esac
+fi
 
 #####################
 # GCC optimizations #
