update xf86-video-ati to version 6.10.0

diff --git a/packages/xf86-video-ati/patches/10_cross-compile.diff b/packages/xf86-video-ati/patches/10_cross-compile.diff
--- a/packages/xf86-video-ati/patches/10_cross-compile.diff
+++ b/packages/xf86-video-ati/patches/10_cross-compile.diff
@@ -1,39 +1,47 @@
-diff -Naur xf86-video-ati-6.9.0.91.orig/configure xf86-video-ati-6.9.0.91/configure
---- xf86-video-ati-6.9.0.91.orig/configure	2008-12-23 12:45:30.000000000 +0100
-+++ xf86-video-ati-6.9.0.91/configure	2008-12-23 12:45:43.000000000 +0100
-@@ -21543,7 +21543,7 @@
+--- xf86-video-ati-6.10.0.orig/configure	2009-01-09 18:46:01.000000000 +0100
++++ xf86-video-ati-6.10.0/configure	2009-01-09 18:46:45.000000000 +0100
+@@ -21389,7 +21389,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
-   $as_echo_n "(cached) " >&6
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
 -  test "$cross_compiling" = yes &&
 +  test "$cross_compiling" = dummy &&
-   { { $as_echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
- $as_echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21571,7 +21571,7 @@
+@@ -21414,7 +21414,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
-   $as_echo_n "(cached) " >&6
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
 -  test "$cross_compiling" = yes &&
 +  test "$cross_compiling" = dummy &&
-   { { $as_echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
- $as_echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21599,7 +21599,7 @@
+@@ -21439,7 +21439,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
-   $as_echo_n "(cached) " >&6
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
 -  test "$cross_compiling" = yes &&
 +  test "$cross_compiling" = dummy &&
-   { { $as_echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
- $as_echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
-@@ -21627,7 +21627,7 @@
+@@ -21464,7 +21464,7 @@
  if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
-   $as_echo_n "(cached) " >&6
+   echo $ECHO_N "(cached) $ECHO_C" >&6
  else
 -  test "$cross_compiling" = yes &&
 +  test "$cross_compiling" = dummy &&
-   { { $as_echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
- $as_echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -23059,7 +23059,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
++  test "$cross_compiling" = dummy &&
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
     { (exit 1); exit 1; }; }
