upgrade xf86-video-ati to 6.8.0

diff --git a/packages/xf86-video-ati/patches/10_cross-compile.diff b/packages/xf86-video-ati/patches/10_cross-compile.diff
--- a/packages/xf86-video-ati/patches/10_cross-compile.diff
+++ b/packages/xf86-video-ati/patches/10_cross-compile.diff
@@ -1,8 +1,35 @@
 diff -Naur xf86-video-ati-X11R7.2-6.6.3.orig/configure xf86-video-ati-X11R7.2-6.6.3/configure
 --- xf86-video-ati-X11R7.2-6.6.3.orig/configure	2007-04-21 11:43:33.000000000 +0200
 +++ xf86-video-ati-X11R7.2-6.6.3/configure	2007-04-21 11:43:45.000000000 +0200
-@@ -21042,7 +21042,7 @@
- if eval "test \"\${$as_ac_File+set}\" = set"; then
+@@ -20801,7 +20801,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
++  test "$cross_compiling" = dummy &&
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -20826,7 +20826,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
++  test "$cross_compiling" = dummy &&
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -20851,7 +20851,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+-  test "$cross_compiling" = yes &&
++  test "$cross_compiling" = dummy &&
+   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+ echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+    { (exit 1); exit 1; }; }
+@@ -22002,7 +22002,7 @@
+ if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
 -  test "$cross_compiling" = yes &&
