bootsplash no longer appended to the initrd with 'make generator' (as before with ext2 initrd)

diff --git a/packages/initrd/install b/packages/initrd/install
--- a/packages/initrd/install
+++ b/packages/initrd/install
@@ -6,4 +6,26 @@ test "$2" != installator && INSTALL="$INSTALL/boot"
 mkdir -p $INSTALL
 cp $BUILD/$1/$1.gz $INSTALL
 
+if [ "$2" != generator ]; then
+  $SCRIPTS/build bootsplash
+  $SCRIPTS/build theme-$THEME
+
+  splashdat=$BUILD/theme-$THEME/bootsplash-$RESOLUTION.dat
+  [ ! -f $splashdat ] && echo "Theme $THEME does not support resolution $RESOLUTION" && exit 1
+
+  cp $splashdat $ROOT/$INSTALL/bootsplash
+  lzma d $ROOT/$INSTALL/$1.gz $ROOT/$INSTALL/$1
+
+  # Append bootsplash to cpio archive
+  cd $ROOT/$INSTALL
+  echo "./bootsplash" | cpio -o -A -H newc -F $ROOT/$INSTALL/$1
+  cd -
+
+  lzma e $ROOT/$INSTALL/$1 $ROOT/$INSTALL/$1.gz
+
+  # Cleanup
+  rm -f $ROOT/$INSTALL/bootsplash
+  rm -f $ROOT/$INSTALL/$1
+fi
+
 exit 0
