use PKG_ARCH instead of arch file in package dir

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -7,16 +7,6 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-if [ -f $PACKAGES/$1/arch ]; then
-  grep -q "$TARGET_ARCH" "$PACKAGES/$1/arch" || exit 0
-  grep -q "\-$TARGET_ARCH" "$PACKAGES/$1/arch" && exit 0
-fi
-
-if [ -f $PACKAGES/$1/platform ]; then
-  grep -q "$TARGET_PLATFORM" "$PACKAGES/$1/platform" || exit 0
-  grep -q "\-$TARGET_PLATFORM" "$PACKAGES/$1/platform" && exit 0
-fi
-
 unset INSTALL
 
 mkdir -p $STAMPS/$1
@@ -39,6 +29,12 @@ if [ ! -f $STAMP ]; then
   export INDENT=$((${INDENT:-1}+$INDENT_SIZE))
 
   get_meta $1
+
+  if [ "$PKG_OPK_ARCH" = unsupported ]; then
+    echo "$1 is not supported on $TARGET_ARCH, aborting."
+    exit 1
+  fi
+
   for p in $PKG_BUILD_DEPENDS; do
     $SCRIPTS/installdev $p
   done
diff --git a/scripts/unpack b/scripts/unpack
--- a/scripts/unpack
+++ b/scripts/unpack
@@ -30,6 +30,11 @@ export INDENT=$((${INDENT:-1}+$INDENT_SIZE))
 
 get_meta $1
 
+if [ "$PKG_OPK_ARCH" = unsupported ]; then
+  echo "$1 is not supported on $TARGET_ARCH, aborting."
+  exit 1
+fi
+
 rm -rf $PKG_BUILD_DIR
 mkdir -p $PKG_BUILD_DIR
 
