list files to be extract from 'url' file (for extraction order), this allows to do MPlayer iso-8859-2 fonts extract in one call.

diff --git a/scripts/extract b/scripts/extract
--- a/scripts/extract
+++ b/scripts/extract
@@ -9,9 +9,16 @@ fi
 
 [ ! -d "$SOURCES/$1" -o ! -f $PACKAGES/$1/url -o ! -d "$3" ] && exit 1
 
-for f in `ls $SOURCES/$1/$2 2>/dev/null`; do
-  if grep -q "/`basename $f`\$" $PACKAGES/$1/url; then
-    case "`basename $f`" in
+for s in `sed 's%.*/\(.*\)\$%\1%' $PACKAGES/$1/url`; do
+  case $s in
+  $2)
+    f="$SOURCES/$1/$s"
+    if [ ! -f $f ]; then
+      echo "error: File $s doesn't exists in package $1 sources directory"
+      echo "have you called scripts/extract before scripts/get ?"
+      exit 1
+    fi
+    case $s in
       *.tar)
         tar xf $f -C $3
         ;;
@@ -34,5 +41,6 @@ for f in `ls $SOURCES/$1/$2 2>/dev/null`; do
         cp -pPR $f $3
         ;;
     esac
-  fi
+    ;;
+  esac
 done
