toolchain: add support for optional MD5 check at package retrieval

diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -4,6 +4,18 @@
 
 NOGET=""
 
+do_md5sum () {
+ [ -z "$PKG_MD5" ] && return 0
+ echo -n "Computing MD5 check for $1 ... "
+ MD5=$(md5sum $1 | cut -d ' ' -f 1)
+ if [ "$MD5" != "$PKG_MD5" ]; then
+  echo "INVALID"
+  exit 1
+ else
+  echo "OK"
+ fi
+}
+
 if [ -z "$1" ]; then
   for i in $PACKAGES/*; do
     GET=yes
@@ -63,6 +75,7 @@ if [ "$DL" = yes ]; then
         exit 1
       fi
     done
+    do_md5sum "$SOURCES/$1/`basename $i`"
     touch $STAMPS_NOARCH/$1/`basename $i`.ok
   done
 
