toolchain: add support for optional SHA256 check at package retrieval

diff --git a/scripts/get b/scripts/get
--- a/scripts/get
+++ b/scripts/get
@@ -16,6 +16,18 @@ do_md5sum () {
  fi
 }
 
+do_sha256sum () {
+ [ -z "$PKG_SHA256" ] && return 0
+ echo -n "Computing SHA256 check for $1 ... "
+ SHA256=$(sha256sum $1 | cut -d ' ' -f 1)
+ if [ "$SHA256" != "$PKG_SHA256" ]; then
+  echo "INVALID"
+  exit 1
+ else
+  echo "OK"
+ fi
+}
+
 if [ -z "$1" ]; then
   for i in $PACKAGES/*; do
     GET=yes
@@ -76,6 +88,7 @@ if [ "$DL" = yes ]; then
       fi
     done
     do_md5sum "$SOURCES/$1/`basename $i`"
+    do_sha256sum "$SOURCES/$1/`basename $i`"
     touch $STAMPS_NOARCH/$1/`basename $i`.ok
   done
 
