move checking if needs to be striped into libstrip script

diff --git a/scripts/libstrip b/scripts/libstrip
--- a/scripts/libstrip
+++ b/scripts/libstrip
@@ -9,6 +9,16 @@ SO=$4
 PROG_SYMS=$5
 LDSCRIPT="$ROOT/$SCRIPTS/ldscript.xs";
 
+if [ ! -f $LIBA ]; then
+  echo "ERROR $LIBA doesn't exists."
+  exit 1
+fi
+
+for i in $PROG; do
+  [ ! -f $LIB -o $i -nt $LIB ] && NEED_TO_STRIP=yes && break
+done
+[ "$NEED_TO_STRIP" != yes ] && exit 0
+
 echo -n "stripping $LIB ..."
 
 for i in $SO; do
