scripts: ensure all packages have a valid section name (otherwise won't appear in menuconfig)

diff --git a/scripts/meta2kconfig b/scripts/meta2kconfig
--- a/scripts/meta2kconfig
+++ b/scripts/meta2kconfig
@@ -159,6 +159,20 @@ EOF
 
 SECTIONS="admin drivers filesystem firmware fonts games libs misc multimedia net perl python sound system utils x11"
 
+# check for packages with invalid section name
+for package in packages/*; do
+  package=`echo $package | sed s:packages/::`
+  [ -f packages/$package/meta ] || continue
+  . packages/$package/meta
+  if [ "$(echo "$SECTIONS" | grep $PKG_SECTION)" != "$SECTIONS" ]; then
+    echo ""
+    echo "Error: $PKG_NAME has an invalid section name"
+    echo " Either fix packages/$package/meta file"
+    echo " or add new section name in scripts/meta2config file."
+    exit 1
+  fi
+done
+
 # generate Kconfig menus for the various sections
 for section in $SECTIONS; do
   echo "menu \"$section\"" >> $KCONFIG
