Fix scripting syntax error

diff --git a/scripts/mplayer-packager b/scripts/mplayer-packager
--- a/scripts/mplayer-packager
+++ b/scripts/mplayer-packager
@@ -19,18 +19,18 @@ TARBALL=$DIR.tar.bz2
 
 echo -n "Downloading MPlayer r$REV source tree...       "
 $SVN export -q $TRUNK $DIR
-[ $? == 0 ] && echo "OK" || (echo "ERROR" && exit 1)
+[ $? = 0 ] && echo "OK" || (echo "ERROR" && exit 1)
 
 mkdir $DIR/.svn
 echo "revision=\"$REV\"" > $DIR/.svn/entries
 
 echo -n "Creating $TARBALL...              "
 tar cjf $TARBALL $DIR
-[ $? == 0 ] && echo "OK" || (echo "ERROR" && exit 1)
+[ $? = 0 ] && echo "OK" || (echo "ERROR" && exit 1)
 
 echo -n "Cleaning up...                                  "
 rm -rf $DIR
-[ $? == 0 ] && echo "OK" || (echo "ERROR" && exit 1)
+[ $? = 0 ] && echo "OK" || (echo "ERROR" && exit 1)
 
 echo
 echo "$TARBALL created successfully!"
