toolchain: about build when no valid config is found

diff --git a/scripts/rootfs b/scripts/rootfs
--- a/scripts/rootfs
+++ b/scripts/rootfs
@@ -2,6 +2,12 @@
 
 . config/options
 
+if [ ! -r build/config/options ]; then
+  echo "Cannot find a valid config (build/config/options is missing!)"
+  echo "Maybe you forgot to run 'make menuconfig' ?"
+  exit 1
+fi
+
 $SCRIPTS/checkdeps build || exit 1
 
 export INSTALL=$ROOTFS
