upgrade xorg-server to 1.5.99.902

diff --git a/packages/xorg-server/patches/50-pkgconfig_gl.diff b/packages/xorg-server/patches/50-pkgconfig_gl.diff
--- a/packages/xorg-server/patches/50-pkgconfig_gl.diff
+++ b/packages/xorg-server/patches/50-pkgconfig_gl.diff
@@ -1,121 +1,121 @@
-diff -Naur xorg-server-1.4.99.906.orig/configure xorg-server-1.4.99.906/configure
---- xorg-server-1.4.99.906.orig/configure	2008-07-23 22:41:01.000000000 +0200
-+++ xorg-server-1.4.99.906/configure	2008-07-23 22:47:25.000000000 +0200
-@@ -30476,12 +30476,12 @@
-     pkg_cv_GL_CFLAGS="$GL_CFLAGS"
-  elif test -n "$PKG_CONFIG"; then
-     if test -n "$PKG_CONFIG" && \
--    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9 gl >= 7.1.0\"") >&5
+diff -Naur xorg-server-1.5.99.902.orig/configure xorg-server-1.5.99.902/configure
+--- xorg-server-1.5.99.902.orig/configure	2009-02-10 21:00:35.000000000 +0100
++++ xorg-server-1.5.99.902/configure	2009-02-10 21:05:32.000000000 +0100
+@@ -30087,12 +30087,12 @@
+         pkg_cv_GL_CFLAGS="$GL_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9 gl >= 7.1.0\"") >&5
 -  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.9 gl >= 7.1.0") 2>&5
-+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9\"") >&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9\"") >&5
 +  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.9") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; then
 -  pkg_cv_GL_CFLAGS=`$PKG_CONFIG --cflags "glproto >= 1.4.9 gl >= 7.1.0" 2>/dev/null`
 +  pkg_cv_GL_CFLAGS=`$PKG_CONFIG --cflags "glproto >= 1.4.9" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -30492,12 +30492,12 @@
-     pkg_cv_GL_LIBS="$GL_LIBS"
-  elif test -n "$PKG_CONFIG"; then
-     if test -n "$PKG_CONFIG" && \
--    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9 gl >= 7.1.0\"") >&5
+@@ -30105,12 +30105,12 @@
+         pkg_cv_GL_LIBS="$GL_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9 gl >= 7.1.0\"") >&5
 -  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.9 gl >= 7.1.0") 2>&5
-+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9\"") >&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.9\"") >&5
 +  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.9") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; then
 -  pkg_cv_GL_LIBS=`$PKG_CONFIG --libs "glproto >= 1.4.9 gl >= 7.1.0" 2>/dev/null`
 +  pkg_cv_GL_LIBS=`$PKG_CONFIG --libs "glproto >= 1.4.9" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -30515,14 +30515,14 @@
+@@ -30129,14 +30129,14 @@
          _pkg_short_errors_supported=no
  fi
          if test $_pkg_short_errors_supported = yes; then
--	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "glproto >= 1.4.9 gl >= 7.1.0" 2>&1`
-+	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "glproto >= 1.4.9" 2>&1`
+-	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glproto >= 1.4.9 gl >= 7.1.0"`
++	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glproto >= 1.4.9"`
          else
--	        GL_PKG_ERRORS=`$PKG_CONFIG --print-errors "glproto >= 1.4.9 gl >= 7.1.0" 2>&1`
-+	        GL_PKG_ERRORS=`$PKG_CONFIG --print-errors "glproto >= 1.4.9" 2>&1`
+-	        GL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glproto >= 1.4.9 gl >= 7.1.0"`
++	        GL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glproto >= 1.4.9"`
          fi
  	# Put the nasty error message in config.log where it belongs
  	echo "$GL_PKG_ERRORS" >&5
  
--	{ { $as_echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.9 gl >= 7.1.0) were not met:
-+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.9) were not met:
+-	{ { echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.9 gl >= 7.1.0) were not met:
++	{ { echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.9) were not met:
  
  $GL_PKG_ERRORS
  
-@@ -30533,7 +30533,7 @@
+@@ -30147,7 +30147,7 @@
  and GL_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  " >&5
--$as_echo "$as_me: error: Package requirements (glproto >= 1.4.9 gl >= 7.1.0) were not met:
-+$as_echo "$as_me: error: Package requirements (glproto >= 1.4.9) were not met:
+-echo "$as_me: error: Package requirements (glproto >= 1.4.9 gl >= 7.1.0) were not met:
++echo "$as_me: error: Package requirements (glproto >= 1.4.9) were not met:
  
  $GL_PKG_ERRORS
  
-@@ -30856,12 +30856,12 @@
-     pkg_cv_GL_CFLAGS="$GL_CFLAGS"
-  elif test -n "$PKG_CONFIG"; then
-     if test -n "$PKG_CONFIG" && \
--    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1 gl >= 7.1.0\"") >&5
--  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1 gl >= 7.1.0") 2>&5
-+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1\"") >&5
+@@ -30374,12 +30374,12 @@
+         pkg_cv_GL_CFLAGS="$GL_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1 dri >= 7.1.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1 dri >= 7.1.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1\"") >&5
 +  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; then
--  pkg_cv_GL_CFLAGS=`$PKG_CONFIG --cflags "glproto >= 1.4.1 gl >= 7.1.0" 2>/dev/null`
+-  pkg_cv_GL_CFLAGS=`$PKG_CONFIG --cflags "glproto >= 1.4.1 dri >= 7.1.0" 2>/dev/null`
 +  pkg_cv_GL_CFLAGS=`$PKG_CONFIG --cflags "glproto >= 1.4.1" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -30872,12 +30872,12 @@
-     pkg_cv_GL_LIBS="$GL_LIBS"
-  elif test -n "$PKG_CONFIG"; then
-     if test -n "$PKG_CONFIG" && \
--    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1 gl >= 7.1.0\"") >&5
--  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1 gl >= 7.1.0") 2>&5
-+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1\"") >&5
+@@ -30392,12 +30392,12 @@
+         pkg_cv_GL_LIBS="$GL_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1 dri >= 7.1.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1 dri >= 7.1.0") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"glproto >= 1.4.1\"") >&5
 +  ($PKG_CONFIG --exists --print-errors "glproto >= 1.4.1") 2>&5
    ac_status=$?
-   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; then
--  pkg_cv_GL_LIBS=`$PKG_CONFIG --libs "glproto >= 1.4.1 gl >= 7.1.0" 2>/dev/null`
+-  pkg_cv_GL_LIBS=`$PKG_CONFIG --libs "glproto >= 1.4.1 dri >= 7.1.0" 2>/dev/null`
 +  pkg_cv_GL_LIBS=`$PKG_CONFIG --libs "glproto >= 1.4.1" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -30895,14 +30895,14 @@
+@@ -30416,14 +30416,14 @@
          _pkg_short_errors_supported=no
  fi
          if test $_pkg_short_errors_supported = yes; then
--	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "glproto >= 1.4.1 gl >= 7.1.0" 2>&1`
-+	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "glproto >= 1.4.1" 2>&1`
+-	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glproto >= 1.4.1 dri >= 7.1.0"`
++	        GL_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "glproto >= 1.4.1"`
          else
--	        GL_PKG_ERRORS=`$PKG_CONFIG --print-errors "glproto >= 1.4.1 gl >= 7.1.0" 2>&1`
-+	        GL_PKG_ERRORS=`$PKG_CONFIG --print-errors "glproto >= 1.4.1" 2>&1`
+-	        GL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glproto >= 1.4.1 dri >= 7.1.0"`
++	        GL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "glproto >= 1.4.1"`
          fi
  	# Put the nasty error message in config.log where it belongs
  	echo "$GL_PKG_ERRORS" >&5
  
--	{ { $as_echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.1 gl >= 7.1.0) were not met:
-+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.1) were not met:
+-	{ { echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.1 dri >= 7.1.0) were not met:
++	{ { echo "$as_me:$LINENO: error: Package requirements (glproto >= 1.4.1) were not met:
  
  $GL_PKG_ERRORS
  
-@@ -30913,7 +30913,7 @@
+@@ -30434,7 +30434,7 @@
  and GL_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  " >&5
--$as_echo "$as_me: error: Package requirements (glproto >= 1.4.1 gl >= 7.1.0) were not met:
-+$as_echo "$as_me: error: Package requirements (glproto >= 1.4.1) were not met:
+-echo "$as_me: error: Package requirements (glproto >= 1.4.1 dri >= 7.1.0) were not met:
++echo "$as_me: error: Package requirements (glproto >= 1.4.1) were not met:
  
  $GL_PKG_ERRORS
  
