qt: add embedded use flag

diff --git a/packages/qt/build b/packages/qt/build
--- a/packages/qt/build
+++ b/packages/qt/build
@@ -4,6 +4,16 @@
 
 require_cxx $1
 
+die () {
+  echo "Unable to build QT: enable either Embedded or X11 flavor and try again"
+  exit 1
+}
+
+# Ensure one of the qualifying flags has been set to build QT.
+if ! pkg_uses $1 embedded && ! pkg_uses $1 xorg; then
+  die
+fi
+
 pkg_uses $1 opengl && \
   CROSS_GL="-opengl" || CROSS_GL="-no-opengl"
 
